name: model_gen_kit
description: Auto Generate Dart Model Class with JsonSerializable, copyWith and toString() method using IntelliJ Plugin.
version: 0.1.1
repository: https://github.com/note11g/DartModelGenerateKit

environment:
  sdk: '>=3.1.1 <4.0.0'
